enum UserActionType {
  GET_OWN_USER_REQUEST = 'GET_OWN_USER_REQUEST',
  GET_OWN_USER_SUCCESS = 'GET_OWN_USER_SUCCESS',
  GET_OWN_USER_FAIL = 'GET_OWN_USER_FAIL',
  GET_OTHER_USER_REQUEST = 'GET_OTHER_USER_REQUEST',
  GET_OTHER_USER_SUCCESS = 'GET_OTHER_USER_SUCCESS',
  GET_OTHER_USER_FAIL = 'GET_OTHER_USER_FAIL',
}

export default UserActionType;