enum NavigationMenuActionType {
  CLICK_PROFILE_TAB = 'CLICK_PROFILE_TAB',
  CLICK_NOTICE_TAB = 'CLICK_NOTICE_TAB',
  CLICK_EXHIBITED_SKILL_TAB = 'CLICK_EXHIBITED_SKILL_TAB',
  CLICK_PURCHASED_SKILL_TAB = 'CLICK_PURCHASED_SKILL_TAB',
}

export default NavigationMenuActionType;