enum NavigationMenuActionType {
  CLICK_PROFILE_TAB = 'CLICK_PROFILE_TAB',
  CLICK_NOTICE_TAB = 'CLICK_NOTICE_TAB',
  CLICK_EXHIBITED_SKILLS_TAB = 'CLICK_EXHIBITED_SKILLS_TAB',
  CLICK_PURCHASED_SKILLS_TAB = 'CLICK_PURCHASED_SKILLS_TAB',
}

export default NavigationMenuActionType;