enum UtariActionType {
  POST_UTARI_SIGN_IN_REQUEST = 'POST_UTARI_SIGN_IN_REQUEST',
  POST_UTARI_SIGN_IN_SUCCESS = 'POST_UTARI_SIGN_IN_SUCCESS',
  POST_UTARI_SIGN_IN_FAIL = 'POST_UTARI_SIGN_IN_FAIL',

  POST_UTARI_SIGN_UP_REQUEST = 'POST_UTARI_SIGN_UP_REQUEST',
  POST_UTARI_SIGN_UP_SUCCESS = 'POST_UTARI_SIGN_UP_SUCCESS',
  POST_UTARI_SIGN_UP_FAIL = 'POST_UTARI_SIGN_UP_FAIL',

  POST_UTARI_BALANCE_REQUEST = 'POST_UTARI_BALANCE_REQUEST',
  POST_UTARI_BALANCE_SUCCESS = 'POST_UTARI_BALANCE_SUCCESS',
  POST_UTARI_BALANCE_FAIL = 'POST_UTARI_BALANCE_FAIL',

  POST_UTARI_TRANSACTION_REQUEST = 'POST_UTARI_TRANSACTION_REQUEST',
  POST_UTARI_TRANSACTION_SUCCESS = 'POST_UTARI_TRANSACTION_SUCCESS',
  POST_UTARI_TRANSACTION_FAIL = 'POST_UTARI_TRANSACTION_FAIL',
}

export default UtariActionType;