enum SkillsActionType {
  GET_TOP_PAGE_SKILLS_REQUEST = 'GET_TOP_PAGE_SKILLS_REQUEST',
  GET_TOP_PAGE_SKILLS_SUCCESS = 'GET_TOP_PAGE_SKILLS_SUCCESS',
  GET_TOP_PAGE_SKILLS_FAIL = 'GET_TOP_PAGE_SKILLS_FAIL',
  GET_SKILLS_REQUEST = 'GET_SKILLS_REQUEST',
  GET_SKILLS_SUCCESS = 'GET_SKILLS_SUCCESS',
  GET_SKILLS_FAIL = 'GET_SKILLS_FAIL',
}

export default SkillsActionType;